export default [
  {
    id: 1,
    category: "Foods",
    type: "Desserts",
    product_name: "Basque Cheesecake",
    price_gbp: 3.4,
    description: "",
    options: "",
  },
  {
    id: 2,
    category: "Foods",
    type: "Desserts",
    product_name: "Torched Brown Sugar Basq",
    price_gbp: 3.7,
    description: "",
    options: "",
  },
  {
    id: 3,
    category: "Foods",
    type: "Desserts",
    product_name: "Matcha Scone",
    price_gbp: 2.4,
    description: "",
    options: "",
  },
  {
    id: 4,
    category: "Foods",
    type: "Desserts",
    product_name: "Plain Scone",
    price_gbp: 2.4,
    description: "",
    options: "",
  },
  {
    id: 5,
    category: "Foods",
    type: "Desserts",
    product_name: "Earl Grey Pound Cake",
    price_gbp: 2.4,
    description: "",
    options: "",
  },
  {
    id: 6,
    category: "Foods",
    type: "Desserts",
    product_name: "Nutty Chocolate Soft Cook",
    price_gbp: 2.4,
    description: "",
    options: "",
  },
  {
    id: 7,
    category: "Foods",
    type: "Savory Dishes",
    product_name: "Sausage Curry Rice",
    price_gbp: 6.4,
    description: "Sausage, Curry, Onion, Carrot, Poached Egg, Eastern Rice",
    options: "Mild spicy, Medium spicy",
  },
  {
    id: 8,
    category: "Foods",
    type: "Savory Dishes",
    product_name: "Vegetable Sausage Curry R",
    price_gbp: 7.1,
    description:
      "Seasonal Vegetables, Sausage, Wild Mushrooms, Curry, Onion, Carrot, Poached Egg, Eastern Rice",
    options: "Mild spicy, Medium spicy",
  },
  {
    id: 9,
    category: "Foods",
    type: "Savory Dishes",
    product_name: "Vegetable Curry Rice",
    price_gbp: 6.6,
    description:
      "Seasonal Vegetables, Wild Mushrooms, Curry, Onion, Carrot, Poached Egg, Eastern Rice",
    options: "Mild spicy, Medium spicy",
  },
  {
    id: 10,
    category: "Foods",
    type: "Savory Dishes",
    product_name: "Shakshuka",
    price_gbp: 6.4,
    description:
      "Tomato, Harissa Sauce, Bell Pepper, Onion, Poached Egg, French Bread",
    options: "Medium spicy!",
  },
  {
    id: 11,
    category: "Foods",
    type: "Savory Dishes",
    product_name: "Shrimp Apple Warm Salad",
    price_gbp: 6.9,
    description:
      "White Shrimp, Fresh Lettuce, Seasonal Vegetables, Sweet Potato, Apple, Sun-dried Tomato, Vinaigrette",
    options: "",
  },
  {
    id: 12,
    category: "Drinks",
    type: "Pour-over Coffee",
    product_name: "Wasted Life Proposal",
    price_gbp: 4.7,
    description:
      "Special Blend, Light-Medium Roast, Berries, Blackcurrant, White Flower",
    options: "Iced, Hot",
  },
  {
    id: 13,
    category: "Drinks",
    type: "Pour-over Coffee",
    product_name: "Life Free Flow Strategy",
    price_gbp: 4.7,
    description:
      "Special Blend, Medium-Dark Roast, Nuts, Butter, Dark Chocolate, Toffee",
    options: "Iced, Hot",
  },
  {
    id: 14,
    category: "Drinks",
    type: "Pour-over Coffee",
    product_name: "Costa Rica Copey Estate",
    price_gbp: 4.9,
    description:
      "Natural Process, Light Roast, Orange, Melon, Sweet Berry, Plum, Brown Sugar, Vanilla, Butter",
    options: "Iced, Hot",
  },
  {
    id: 15,
    category: "Drinks",
    type: "Pour-over Coffee",
    product_name: "Colombia Nariño Washed",
    price_gbp: 4.9,
    description:
      "Washed Process, Light-Medium Roast, Brown Sugar, Roasted Walnut, Chocolate",
    options: "Iced, Hot",
  },
  {
    id: 16,
    category: "Drinks",
    type: "Pour-over Coffee",
    product_name: "Papua New Guinea Nabire",
    price_gbp: 4.9,
    description: "Washed Process, Medium Roast, Nuts, Butter, Honey, Licorice",
    options: "Iced, Hot",
  },
  {
    id: 17,
    category: "Drinks",
    type: "Black Coffee",
    product_name: "Cold Brew Coffee",
    price_gbp: 5.4,
    description:
      "Special Blend, Medium-Dark Roast, Nuts, Butter, Dark Chocolate, Toffee",
    options: "Iced, Hot",
  },
  {
    id: 18,
    category: "Drinks",
    type: "Black Coffee",
    product_name: "Americano",
    price_gbp: 3.4,
    description: "",
    options: "Iced, Hot",
  },
  {
    id: 19,
    category: "Drinks",
    type: "Black Coffee",
    product_name: "Sparkling Americano",
    price_gbp: 3.7,
    description: "",
    options: "Iced",
  },
  {
    id: 20,
    category: "Drinks",
    type: "Black Coffee",
    product_name: "Sicilian Coffee",
    price_gbp: 4.2,
    description: "",
    options: "Iced",
  },
  {
    id: 21,
    category: "Drinks",
    type: "Black Coffee",
    product_name: "Apple Special Blend",
    price_gbp: 4.2,
    description: "",
    options: "Iced",
  },
  {
    id: 22,
    category: "Drinks",
    type: "Black Coffee",
    product_name: "Lemon Special Blend",
    price_gbp: 3.9,
    description: "",
    options: "Iced",
  },
];
