export default [
  {
    id: 1,
    category: "Drinks",
    type: "Pour-over Coffee",
    product_name: "Wasted Life Proposal",
    price_gbp: 4.7,
    description:
      "Special Blend, Light-Medium Roast, Berries, Blackcurrant, White Flower",
    options: "Iced, Hot",
    image: "",
  },
  {
    id: 2,
    category: "Drinks",
    type: "Pour-over Coffee",
    product_name: "Life Free Flow Strategy",
    price_gbp: 4.7,
    description:
      "Special Blend, Medium-Dark Roast, Nuts, Butter, Dark Chocolate, Toffee",
    options: "Iced, Hot",
    image: "",
  },
  {
    id: 3,
    category: "Drinks",
    type: "Pour-over Coffee",
    product_name: "Costa Rica Copey Estate",
    price_gbp: 4.9,
    description:
      "Natural Process, Light Roast, Orange, Melon, Sweet Berry, Plum, Brown Sugar, Vanilla, Butter",
    options: "Iced, Hot",
    image: "",
  },
  {
    id: 4,
    category: "Drinks",
    type: "Pour-over Coffee",
    product_name: "Colombia Nariño Washed",
    price_gbp: 4.9,
    description:
      "Washed Process, Light-Medium Roast, Brown Sugar, Butter, Citrus, Roasted Walnut, Chocolate",
    options: "Iced, Hot",
    image: "",
  },
  {
    id: 5,
    category: "Drinks",
    type: "Pour-over Coffee",
    product_name: "Papua New Guinea Nabire",
    price_gbp: 4.9,
    description: "Washed Process, Medium Roast, Nuts, Butter, Honey, Licorice",
    options: "Iced, Hot",
    image: "",
  },
  {
    id: 6,
    category: "Drinks",
    type: "Black Coffee",
    product_name: "Cold Brew Coffee",
    price_gbp: 5.4,
    description:
      "Special Blend, Medium-Dark Roast, Nuts, Butter, Dark Chocolate, Toffee",
    options: "Iced, Hot",
    image: "Cold Brew Coffee.jpg",
  },
  {
    id: 7,
    category: "Drinks",
    type: "Black Coffee",
    product_name: "Americano",
    price_gbp: 3.4,
    description: "",
    options: "Iced, Hot",
    image: "",
  },
  {
    id: 8,
    category: "Drinks",
    type: "Black Coffee",
    product_name: "Sparkling Americano",
    price_gbp: 3.7,
    description: "",
    options: "Iced",
    image: "",
  },
  {
    id: 9,
    category: "Drinks",
    type: "Black Coffee",
    product_name: "Sicilian Coffee",
    price_gbp: 4.2,
    description: "",
    options: "Iced",
    image: "",
  },
  {
    id: 10,
    category: "Drinks",
    type: "Black Coffee",
    product_name: "Apple Special Blend",
    price_gbp: 4.2,
    description: "",
    options: "Iced",
    image: "",
  },
  {
    id: 11,
    category: "Drinks",
    type: "Black Coffee",
    product_name: "Lemon Special Blend",
    price_gbp: 3.9,
    description: "",
    options: "Iced",
    image: "",
  },
  {
    id: 12,
    category: "Drinks",
    type: "Milk Coffee",
    product_name: "Cappuccino",
    price_gbp: 3.9,
    description: "",
    options: "Hot",
    image: "",
  },
  {
    id: 13,
    category: "Drinks",
    type: "Milk Coffee",
    product_name: "Coffee Latte",
    price_gbp: 3.9,
    description: "",
    options: "Iced, Hot",
    image: "",
  },
  {
    id: 14,
    category: "Drinks",
    type: "Milk Coffee",
    product_name: "Ice Cube Coffee Latte",
    price_gbp: 4.2,
    description: "",
    options: "Iced",
    image: "",
  },
  {
    id: 15,
    category: "Drinks",
    type: "Milk Coffee",
    product_name: "Sea Salt Caramel Coffee Latte",
    price_gbp: 4.2,
    description: "",
    options: "Iced, Hot",
    image: "",
  },
  {
    id: 16,
    category: "Drinks",
    type: "Milk Coffee",
    product_name: "Mocha Coffee Latte",
    price_gbp: 4.2,
    description: "",
    options: "Iced, Hot",
    image: "Mocha Coffee Latte.jpg",
  },
  {
    id: 17,
    category: "Drinks",
    type: "Milk Coffee",
    product_name: "Shizuoka Matcha Coffee Latte",
    price_gbp: 4.4,
    description: "",
    options: "Iced, Hot",
    image: "",
  },
  {
    id: 18,
    category: "Drinks",
    type: "Milk Coffee",
    product_name: "Hojicha Coffee Latte",
    price_gbp: 4.4,
    description: "",
    options: "Iced, Hot",
    image: "",
  },
  {
    id: 19,
    category: "Drinks",
    type: "Milk Coffee",
    product_name: "Torched Brown Sugar Coffee Latte",
    price_gbp: 4.4,
    description: "",
    options: "Iced, Hot",
    image: "",
  },
  {
    id: 20,
    category: "Drinks",
    type: "Milk Coffee",
    product_name: "Honey Cinnamon Coffee Latte",
    price_gbp: 4.4,
    description: "",
    options: "Iced, Hot",
    image: "",
  },
  {
    id: 21,
    category: "Drinks",
    type: "Milk",
    product_name: "Cloud Fresh Milk",
    price_gbp: 3.7,
    description: "",
    options: "Iced, Hot",
    image: "",
  },
  {
    id: 22,
    category: "Drinks",
    type: "Milk",
    product_name: "Charcoal Brown Sugar Milk Tea",
    price_gbp: 4.2,
    description: "",
    options: "Iced, Hot",
    image: "",
  },
  {
    id: 23,
    category: "Drinks",
    type: "Milk",
    product_name: "Shizuoka Matcha Milk",
    price_gbp: 4.4,
    description: "",
    options: "Iced, Hot",
    image: "",
  },
  {
    id: 24,
    category: "Drinks",
    type: "Milk",
    product_name: "Hojicha Milk",
    price_gbp: 4.4,
    description: "",
    options: "Iced, Hot",
    image: "",
  },
  {
    id: 25,
    category: "Drinks",
    type: "Milk",
    product_name: "Torched Brown Sugar Milk",
    price_gbp: 4.2,
    description: "",
    options: "Iced, Hot",
    image: "",
  },
  {
    id: 26,
    category: "Drinks",
    type: "Milk",
    product_name: "Chocolate Milk",
    price_gbp: 4.2,
    description: "",
    options: "Iced, Hot",
    image: "Chocolate Milk.jpg",
  },
  {
    id: 27,
    category: "Drinks",
    type: "Milk",
    product_name: "Sea Salt Caramel Milk",
    price_gbp: 4.2,
    description: "",
    options: "Iced, Hot",
    image: "",
  },
  {
    id: 28,
    category: "Drinks",
    type: "Milk",
    product_name: "Apple Milk",
    price_gbp: 3.9,
    description: "",
    options: "Iced",
    image: "",
  },
  {
    id: 29,
    category: "Drinks",
    type: "Milk",
    product_name: "Strawberry Milk",
    price_gbp: 3.9,
    description: "",
    options: "Iced",
    image: "",
  },
  {
    id: 30,
    category: "Drinks",
    type: "Specialty Sparkling Drinks",
    product_name: "Strawberry Calpis Soda",
    price_gbp: 3.9,
    description: "",
    options: "Iced",
    image: "",
  },
  {
    id: 31,
    category: "Drinks",
    type: "Specialty Sparkling Drinks",
    product_name: "Peach Calpis Soda",
    price_gbp: 3.9,
    description: "",
    options: "Iced",
    image: "",
  },
  {
    id: 32,
    category: "Drinks",
    type: "Specialty Sparkling Drinks",
    product_name: "Mango Calpis Soda",
    price_gbp: 3.9,
    description: "",
    options: "Iced",
    image: "",
  },
  {
    id: 33,
    category: "Drinks",
    type: "Specialty Sparkling Drinks",
    product_name: "Blueberry Calpis Soda",
    price_gbp: 3.9,
    description: "",
    options: "Iced",
    image: "",
  },
  {
    id: 34,
    category: "Drinks",
    type: "Specialty Sparkling Drinks",
    product_name: "Apple Soda",
    price_gbp: 3.9,
    description: "",
    options: "Iced",
    image: "",
  },
  {
    id: 35,
    category: "Drinks",
    type: "Specialty Sparkling Drinks",
    product_name: "Yuzu Soda",
    price_gbp: 3.9,
    description: "",
    options: "Iced",
    image: "",
  },
  {
    id: 36,
    category: "Drinks",
    type: "Taiwan Specialty Tea",
    product_name: "Alishan Oolong Tea",
    price_gbp: 3.9,
    description: "Semi-fermented / Rich floral aroma, Lychee fruit aroma",
    options: "Iced, Hot",
    image: "",
  },
  {
    id: 37,
    category: "Drinks",
    type: "Taiwan Specialty Tea",
    product_name: "Yuchi Four Seasons Spring Green Tea",
    price_gbp: 3.9,
    description: "Semi-fermented / Pomelo, Wild ginger, Jasmine floral aroma",
    options: "Iced, Hot",
    image: "",
  },
  {
    id: 38,
    category: "Drinks",
    type: "Taiwan Specialty Tea",
    product_name: "Lishan High Mountain Tea",
    price_gbp: 4.2,
    description:
      "Lightly fermented / Deep aroma of Oolong tea, Fresh scent of high mountain tea, Full of fruity aroma",
    options: "",
    image: "",
  },
  {
    id: 39,
    category: "Drinks",
    type: "Taiwan Specialty Tea",
    product_name: "Tongluo Handpicked Oriental Beauty Tea",
    price_gbp: 4.2,
    description: "Heavily fermented / Ripe fruit aroma",
    options: "",
    image: "",
  },
  {
    id: 40,
    category: "Drinks",
    type: "Taiwan Specialty Tea",
    product_name: "Pinglin Pouchong Tea",
    price_gbp: 4.2,
    description:
      "Semi-fermented / Light roast cane sugar sweetness, Gardenia jasmine aroma",
    options: "",
    image: "",
  },
  {
    id: 41,
    category: "Drinks",
    type: "Taiwan Specialty Tea",
    product_name: "Sun Moon Lake Assam Red Tea No.8",
    price_gbp: 3.9,
    description: "Fully fermented / Malt aroma, Milk candy sweetness",
    options: "Iced, Hot",
    image: "Sun Moon Lake Assam Red Tea No.8.jpg",
  },
  {
    id: 42,
    category: "Drinks",
    type: "Fresh Juice",
    product_name: "Nutty Banana Milk",
    price_gbp: 4.4,
    description: "",
    options: "Iced",
    image: "",
  },
  {
    id: 43,
    category: "Drinks",
    type: "Fresh Juice",
    product_name: "Banana Apple Milk",
    price_gbp: 4.4,
    description: "",
    options: "Iced",
    image: "",
  },
  {
    id: 44,
    category: "Drinks",
    type: "Fresh Juice",
    product_name: "Kiwi Banana Yogurt Drink",
    price_gbp: 4.4,
    description: "",
    options: "Iced",
    image: "Kiwi Banana Yogurt Drink.jpg",
  },
  {
    id: 45,
    category: "Drinks",
    type: "Other Drinks",
    product_name: "Yuzu Tea",
    price_gbp: 3.9,
    description: "",
    options: "Iced, Hot",
    image: "",
  },
  {
    id: 46,
    category: "Drinks",
    type: "Other Drinks",
    product_name: "Apple Tea",
    price_gbp: 3.9,
    description: "",
    options: "Iced, Hot",
    image: "",
  },
  {
    id: 47,
    category: "Drinks",
    type: "Other Drinks",
    product_name: "Apple Juice",
    price_gbp: 3.4,
    description: "",
    options: "Iced",
    image: "",
  },
  {
    id: 48,
    category: "Drinks",
    type: "Other Drinks",
    product_name: "Calpis",
    price_gbp: 3.4,
    description: "",
    options: "Iced",
    image: "",
  },
  {
    id: 49,
    category: "Drinks",
    type: "Alcoholic Special Blend",
    product_name: "Wave",
    price_gbp: 6.1,
    description: "",
    options: "No alcohol -£1, Extra alcohol +£1",
    image: "",
  },
  {
    id: 50,
    category: "Drinks",
    type: "Alcoholic Special Blend",
    product_name: "Night Dive",
    price_gbp: 6.1,
    description: "",
    options: "No alcohol -£1, Extra alcohol +£1",
    image: "",
  },
  {
    id: 51,
    category: "Drinks",
    type: "Alcoholic Special Blend",
    product_name: "Morning Dive",
    price_gbp: 6.1,
    description: "",
    options: "No alcohol -£1, Extra alcohol +£1",
    image: "",
  },
  {
    id: 52,
    category: "Drinks",
    type: "Alcoholic Special Blend",
    product_name: "Lanyu Blue",
    price_gbp: 6.1,
    description: "",
    options: "No alcohol -£1, Extra alcohol +£1",
    image: "",
  },
  {
    id: 53,
    category: "Drinks",
    type: "Alcoholic Special Blend",
    product_name: "Burnt Island",
    price_gbp: 6.1,
    description: "",
    options: "No alcohol -£1, Extra alcohol +£1",
    image: "",
  },
  {
    id: 54,
    category: "Foods",
    type: "Desserts",
    product_name: "Basque Cheesecake",
    price_gbp: 3.4,
    description: "",
    options: "",
    image: "Basque Cheesecake.jpg",
  },
  {
    id: 55,
    category: "Foods",
    type: "Desserts",
    product_name: "Torched Brown Sugar Basque Cheesecake",
    price_gbp: 3.7,
    description: "",
    options: "",
    image: "",
  },
  {
    id: 56,
    category: "Foods",
    type: "Desserts",
    product_name: "Matcha Scone",
    price_gbp: 2.4,
    description: "",
    options: "",
    image: "Matcha Scone.jpg",
  },
  {
    id: 57,
    category: "Foods",
    type: "Desserts",
    product_name: "Plain Scone",
    price_gbp: 2.4,
    description: "",
    options: "",
    image: "Plain Scone.jpg",
  },
  {
    id: 58,
    category: "Foods",
    type: "Desserts",
    product_name: "Earl Grey Pound Cake",
    price_gbp: 2.4,
    description: "",
    options: "",
    image: "Earl Grey Pound Cake",
  },
  {
    id: 59,
    category: "Foods",
    type: "Desserts",
    product_name: "Nutty Chocolate Soft Cookie",
    price_gbp: 2.4,
    description: "",
    options: "",
    image: "Nutty Chocolate Soft Cookie.jpg",
  },
  {
    id: 60,
    category: "Foods",
    type: "Savory Dishes",
    product_name: "Sausage Curry Rice",
    price_gbp: 6.4,
    description: "Sausage, Curry, Onion, Carrot, Poached Egg, Eastern Rice",
    options: "Mild spicy, Medium spicy",
    image: "",
  },
  {
    id: 61,
    category: "Foods",
    type: "Savory Dishes",
    product_name: "Vegetable Sausage Curry Rice",
    price_gbp: 7.1,
    description:
      "Seasonal Vegetables, Sausage, Wild Mushrooms, Curry, Onion, Carrot, Poached Egg, Eastern Rice",
    options: "Mild spicy, Medium spicy",
    image: "Vegetable Sausage Curry Rice.jpg",
  },
  {
    id: 62,
    category: "Foods",
    type: "Savory Dishes",
    product_name: "Vegetable Curry Rice",
    price_gbp: 6.6,
    description:
      "Seasonal Vegetables, Wild Mushrooms, Curry, Onion, Carrot, Poached Egg, Eastern Rice",
    options: "Mild spicy, Medium spicy",
    image: "",
  },
  {
    id: 63,
    category: "Foods",
    type: "Savory Dishes",
    product_name: "Shakshuka",
    price_gbp: 6.4,
    description:
      "Tomato, Harissa Sauce, Bell Pepper, Onion, Poached Egg, French Bread",
    options: "Medium spicy!",
    image: "Shakshuka.jpg",
  },
  {
    id: 64,
    category: "Foods",
    type: "Savory Dishes",
    product_name: "Shrimp Apple Warm Salad",
    price_gbp: 6.9,
    description:
      "White Shrimp, Fresh Lettuce, Seasonal Vegetables, Sweet Potato, Apple, Sun-dried Tomato, Vinaigrette",
    options: "",
    image: "Shrimp Apple Warm Salad.jpg",
  },
  {
    id: 65,
    category: "Foods",
    type: "Savory Dishes",
    product_name: "Shrimp Rice Ball with Mentaiko",
    price_gbp: 6.1,
    description:
      "Sesame Oil, Seaweed Crisp, White Shrimp, Furikake, Mentaiko Sauce, Fresh Lettuce, Sun-dried Tomato",
    options: "",
    image: "Shrimp Rice Ball with Mentaiko.jpg",
  },
  {
    id: 66,
    category: "Foods",
    type: "Savory Dishes",
    product_name: "Shrimp Avocado Open-faced Sandwich",
    price_gbp: 7.1,
    description:
      "White Shrimp, Pear Chutney, Scrambled Eggs, Fresh Lettuce, Sun-dried Tomato, Vinaigrette, Sourdough Bread",
    options: "",
    image: "Shrimp Avocado Open-faced Sandwich.jpg",
  },
  {
    id: 67,
    category: "Foods",
    type: "Savory Dishes",
    product_name: "Mushroom Poached Egg Open-faced Sandwich",
    price_gbp: 6.4,
    description:
      "Wild Mushrooms, Poached Egg, Italian Cheese Sauce, Fresh Lettuce, Sun-dried Tomato, Vinaigrette, Sourdough Bread",
    options: "",
    image: "Mushroom Poached Egg Open-faced Sandwich.jpg",
  },
  {
    id: 68,
    category: "Foods",
    type: "Savory Dishes",
    product_name: "Shrimp",
    price_gbp: 2,
    description: "",
    options: "",
    image: "",
  },
  {
    id: 69,
    category: "Foods",
    type: "Savory Dishes",
    product_name: "Poached Egg",
    price_gbp: 0.5,
    description: "",
    options: "",
    image: "",
  },
  {
    id: 70,
    category: "Foods",
    type: "Savory Dishes",
    product_name: "Bread",
    price_gbp: 0.5,
    description: "",
    options: "",
    image: "",
  },
  {
    id: 71,
    category: "Foods",
    type: "Savory Dishes",
    product_name: "White Rice",
    price_gbp: 0.5,
    description: "",
    options: "",
    image: "",
  },
  {
    id: 72,
    category: "Foods",
    type: "Sweets",
    product_name: "Banana Strawberry Yogurt Bowl",
    price_gbp: 4.4,
    description: "Yogurt, Banana, Strawberry Jam, Crunchy Granola, Nuts",
    options: "",
    image: "",
  },
  {
    id: 73,
    category: "Foods",
    type: "Sweets",
    product_name: "Mango Kiwi Yogurt Bowl",
    price_gbp: 4.4,
    description: "Yogurt, Kiwi, Mango Sauce, Crunchy Granola, Nuts",
    options: "",
    image: "Mango Kiwi Yogurt Bowl.jpg",
  },
  {
    id: 74,
    category: "Foods",
    type: "Sweets",
    product_name: "Chocolate Banana Open-faced Sandwich",
    price_gbp: 6.1,
    description:
      "Peanut Butter, Banana, Nuts, Fresh Lettuce, Sun-dried Tomato, Vinaigrette, Sourdough Bread, Yogurt",
    options: "Chocolate Banana Open-faced Sandwich.jpg",
    image: "",
  },
  {
    id: 75,
    category: "Foods",
    type: "Sweets",
    product_name: "Peanut Butter Banana Open-faced Sandwich",
    price_gbp: 6.1,
    description:
      "Peanut Butter, Banana, Nuts, Fresh Lettuce, Sun-dried Tomato, Vinaigrette, Sourdough Bread, Yogurt",
    options: "",
    image: "",
  },
  {
    id: 76,
    category: "Foods",
    type: "Sweets",
    product_name: "Apple Caramel Open-faced Sandwich",
    price_gbp: 6.1,
    description:
      "Italian Cheese Sauce, Apple, Honey, Nuts, Fresh Lettuce, Sun-dried Tomato, Vinaigrette, Sourdough Bread, Yogurt",
    options: "",
    image: "",
  },
];
